server:
  port: 8005

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: dkwktm45

  mvc:
    view:
      suffix: .html
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
    add-mappings: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html